### ISSUE TITLE
Contrast Issues

### ISSUE THREAD

**Issue by jxc876** [Jawad762/Portfolio#1]
Contrast Issues

- Mac OS (Chrome browser)

<img width="851" alt="image" src="https://github.com/user-attachments/assets/67bc5576-994f-41bf-8102-f7a35afff2e4">

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/aec3e403-08a8-4185-a14f-d5c479036d60">

**Comment by Jawad762** [comment]
Pushed out a potential fix, could you try again and tell me what you see
please ?

**Comment by Jawad762** [comment]
fixed
